import { Geist_Mono, Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const customiseBengaliFont = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata = {
  title: "Bazar dor web App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${customiseBengaliFont.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
